{% set name = "pennylane-cirq" %}
{% set version = "0.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane-cirq/archive/v{{ version }}.tar.gz
  sha256: 13c125fb18a206e72788d7d5f6c304251c2d3847241558631828e946d6edc973

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - cirq-core >=0.10
    - cirq-pasqal >=0.10
    - pennylane >=0.17
    - python >=3.9

test:
  imports:
    - pennylane_cirq
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://xanadu.ai
  summary: PennyLane plugin for Cirq
  description: |
    The PennyLane-Cirq plugin integrates Google's Cirq software library
    with PennyLane's quantum machine learning capabilities.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/PennyLaneAI/pennylane-cirq
  doc_url: https://pennylane-cirq.readthedocs.io/

extra:
  recipe-maintainers:
    - BastianZim
